### PR TITLE
Resolved Deprecations and Warnings.

### PR DESCRIPTION
**Pull request by TimvanSteenbergen**
- Added a image for Questionmark
- Replaced action-less-buttons with images and gave them class 'btn btn-transparent'
- Revoked user TestRunner's role from IVK_FindAllTests.
- Replaced floats by decimals
As far as I can see, everything works like it used to.

### CODE REVIEW

**Comment by RoelandSalij** [comment]
Hi Tim,
Thanks for your contribution!
- I noticed that the conditional visibility isn't set correctly for the 'remove' image. 
- For the images: the quality isn't that good(for the question mark). Can you take the same approach as is done for the clock: Setting the glyphicon classes on a container element.

Is it possible to change these two things?

**Comment by TimvanSteenbergen** [comment]
Roeland,

Sure, I will give it a go. Wanted to do it today, but did not manage. 

Are you not able to make those modifications by yourself? 

Regards,

Tim

 

Van: Roeland Salij [mailto:notifications@github.com] 
Verzonden: maandag 18 december 2017 17:22
Aan: mendix/UnitTesting
CC: Tim van Steenbergen; Author
Onderwerp: Re: [mendix/UnitTesting] Resolved Deprecations and Warnings. (#9)

 

Hi Tim,
Thanks for your contribution!

*	I noticed that the conditional visibility isn't set correctly for the 'remove' image.
*	For the images: the quality isn't that good(for the question mark). Can you take the same approach as is done for the clock: Setting the glyphicon classes on a container element.

Is it possible to change these two things?

**Comment by TimvanSteenbergen** [comment]
Roeland,

 

 

*	I noticed that the conditional visibility isn't set correctly for the 'remove' image.

            What remove image. It is unclear what item on what page you are talking about.

*	For the images: the quality isn't that good(for the question mark). Can you take the same approach as is done for the clock: Setting the glyphicon classes on a container element.

            Quality looks fine to me and the same as the check_mark_icon_16 and the x_mark_icon_16. Of course you are free to upload any other icon to suit your purpose, but I would advise to handle these three in a simular approach instead of giving the question a separate approach simular to the clock, that is used somewhere else.



 

Regards,

Tim

 

Van: Roeland Salij [mailto:notifications@github.com] 
Verzonden: maandag 18 december 2017 17:22
Aan: mendix/UnitTesting
CC: Tim van Steenbergen; Author
Onderwerp: Re: [mendix/UnitTesting] Resolved Deprecations and Warnings. (#9)

 

Hi Tim,
Thanks for your contribution!

*	I noticed that the conditional visibility isn't set correctly for the 'remove' image.
*	For the images: the quality isn't that good(for the question mark). Can you take the same approach as is done for the clock: Setting the glyphicon classes on a container element.

Is it possible to change these two things?

**Comment by TimvanSteenbergen** [comment]
Roeland,

You can also give me a call if you'dd like, 0627652529 in NL. These two minor issues will then be easily solved and the pullrequest merged.

Regards,

Tim

 

Van: Tim van Steenbergen [mailto:tim@tieka.nl] 
Verzonden: donderdag 21 december 2017 12:20
Aan: 'mendix/UnitTesting'
Onderwerp: RE: [mendix/UnitTesting] Resolved Deprecations and Warnings. (#9)

 

Roeland,

 

 

*	I noticed that the conditional visibility isn't set correctly for the 'remove' image.

            What remove image. It is unclear what item on what page you are talking about.

*	For the images: the quality isn't that good(for the question mark). Can you take the same approach as is done for the clock: Setting the glyphicon classes on a container element.

            Quality looks fine to me and the same as the check_mark_icon_16 and the x_mark_icon_16. Of course you are free to upload any other icon to suit your purpose, but I would advise to handle these three in a simular approach instead of giving the question a separate approach simular to the clock, that is used somewhere else.



 

Regards,

Tim

 

Van: Roeland Salij [mailto:notifications@github.com] 
Verzonden: maandag 18 december 2017 17:22
Aan: mendix/UnitTesting
CC: Tim van Steenbergen; Author
Onderwerp: Re: [mendix/UnitTesting] Resolved Deprecations and Warnings. (#9)

 

Hi Tim,
Thanks for your contribution!

*	I noticed that the conditional visibility isn't set correctly for the 'remove' image.
*	For the images: the quality isn't that good(for the question mark). Can you take the same approach as is done for the clock: Setting the glyphicon classes on a container element.

Is it possible to change these two things?

**Comment by RoelandSalij** [comment]
Hi Tim,
Does it work for you if we discuss this prior to or after the meetup @ Mendix today?

- With the remove image I mean the red cross.
- Using glyphicons has a couple of advantages over using images from a UI perspective as the look and feel can be influenced by the css of your application.

**Comment by TimvanSteenbergen** [comment]
Hi Roeland. We started a new project today so as of now I am extra interested in UnitTesting. I found the visibility flaw you mentioned. So I repaired that one.
The question mark is now nice looking image. Agreed that Glyphicons can get customized using css. But I can't imagine this being a problem in any project using this Great module.

**Comment by TimvanSteenbergen** [comment]
Are you ever going to import this branch?

**Comment by RoelandSalij** [comment]
Yes,
I will continue with the merging process this week.

Van: Tim van Steenbergen <notifications@github.com>
Verzonden: woensdag 4 april 2018 08:25
Aan: mendix/UnitTesting <UnitTesting@noreply.github.com>
CC: Roeland Salij <Roeland.Salij@mendix.com>; Comment <comment@noreply.github.com>
Onderwerp: Re: [mendix/UnitTesting] Resolved Deprecations and Warnings. (#9)


Are you ever going to import this branch?

**Pull request merged**
